#!/usr/bin/env bash
# script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
g=0
while [ $((g++)) -lt 10 ]; do
	echo Best School
	if [ $g -eq 9 ]; then
		echo Hg
	fi
done
